鈴木このみ Discs
ProjectAnni/repo pull request #106
Opened 2022-05-17 17:46 UTC by Yesterday17

2022-05-18 09:22 UTC, Last-Order requested changes

2022-05-18 09:22 UTC, Last-Order commented on album/ZMCZ-8798.toml
> +title = "私がモテないのはどう考えてもお前らが悪い （鈴木このみぼっちver.）"
```suggestion
title = "私がモテないのはどう考えてもお前らが悪い （鈴木このみぼっちver.）"
artist = "鈴木このみ"
```

2022-05-18 09:22 UTC, Last-Order commented on album/ZMCZ-8798.toml
> +title = "私がモテないのはどう考えてもお前らが悪い （キバオブアキバぼっちver.）"
```suggestion
title = "私がモテないのはどう考えてもお前らが悪い （キバオブアキバぼっちver.）"
artist = "キバオブアキバ"
```

2022-05-18 09:22 UTC, Last-Order commented on album/USSW-0166.toml
> +tags = ["この世の果てで恋を唄う少女 YU-NO", "ED"]
テレビアニメ『この世の果てで恋を唄う少女YU-NO』現世編

2022-05-18 09:22 UTC, Last-Order commented on album/USSW-0166.toml
> +tags = ["この世の果てで恋を唄う少女 YU-NO", "ED"]
还有个异世界篇的tie 只有album里有 看看要不要标一下
MOTHER	テレビアニメ『この世の果てで恋を唄う少女YU-NO』異世界編オープニングテーマ

2022-05-18 09:22 UTC, Last-Order commented on album/ZMCZ-11835.toml
> +title = "THERE IS A REASON"
这歌还挺有名的
劇場アニメ『ノーゲーム・ノーライフ ゼロ』テーマソング

2022-05-18 09:38 UTC, Yesterday17 commented on album/ZMCZ-11835.toml
> +title = "THERE IS A REASON"
一个问题是，之前已经以单曲形式发行过的曲在album里要不要把之前的tag再打一遍（

2022-05-18 09:53 UTC, Last-Order commented on album/ZMCZ-11835.toml
> +title = "THERE IS A REASON"
我觉得不用 这个是因为只有album里有我才说的

2022-05-19 14:11 UTC, Last-Order approved these changes

2022-05-19 15:03 UTC, merged