220528 Add some discs
ProjectAnni/repo pull request #113
Opened 2022-05-28 07:43 UTC by Last-Order

2022-06-12 15:46 UTC, Yesterday17 requested changes

2022-06-12 15:46 UTC, Yesterday17 commented on album/SRCL-11792.toml
> +type = "instrumental"
`instrumental` or `absolute`?

2022-06-12 15:46 UTC, Yesterday17 commented on album/VVCL-2055.toml
> +tags = ["TrySail", "TVアニメ「阿波連さんははかれない」"]
Etoile 是 `TVアニメ「阿波連さんははかれない」` 的吗（？

2022-06-13 16:44 UTC, SeraphJACK approved these changes

2022-06-14 09:29 UTC, tuzi3040 approved these changes

2022-06-14 12:00 UTC, merged