鈴木みのり Discs
ProjectAnni/repo pull request #120
Opened 2022-06-02 06:53 UTC by Yesterday17

2022-06-02 06:54 UTC, Yesterday17 commented on album/VTZL-202.toml
> +catalog = "TODO"
蹲一个实际的 catalog

2022-06-02 14:21 UTC, Last-Order requested changes

2022-06-02 14:21 UTC, Last-Order commented on album/VTZL-191.toml
> +type = "normal"
```suggestion
type = "normal"
edition = "初回限定盤"
```

2022-06-02 14:21 UTC, Last-Order commented on album/VTZL-202.toml
> +catalog = "TODO"
VTCY-146

2022-06-28 15:46 UTC, Last-Order approved these changes

2022-06-28 16:15 UTC, merged