南條愛乃 Discs
ProjectAnni/repo pull request #128
Opened 2022-06-29 10:28 UTC by Yesterday17

2022-07-03 09:40 UTC, Last-Order requested changes

2022-07-03 09:40 UTC, Last-Order commented on album/GNCA-0647.toml
> +date = 2021-11-20
```suggestion
date = 2021-11-10
```

2022-07-03 09:40 UTC, Last-Order commented on album/GNCA-1549.toml
> +title = "一切は物語"
yanaginagi：我活在伴奏里

2022-07-03 09:40 UTC, Last-Order commented on album/GNCA-1549.toml
> +type = "instrumental"
absolute?

2022-07-07 02:31 UTC, Yesterday17 commented on album/GNCA-1549.toml
> +title = "一切は物語"
草 确实）

2022-07-07 02:41 UTC, Last-Order approved these changes

2022-07-07 02:41 UTC, merged