このはな綺譚 discs
ProjectAnni/repo pull request #129
Opened 2022-07-03 02:57 UTC by snylonue

2022-07-03 14:30 UTC, Yesterday17 commented on album/LACM-14667.toml
> +tags = ["OP"]
四首都是OP吗（？

2022-07-07 11:48 UTC, snylonue commented on album/LACM-14667.toml
> +tags = ["OP"]
看了下动画只有 `ココロニツボミ` 是
当时以为和 ED 一样有多首（

2022-07-11 15:44 UTC, Yesterday17 requested changes

2022-07-11 15:44 UTC, Yesterday17 commented on album/LACM-14667.toml
> +tags = ["OP"]
```suggestion
tags = ["TVアニメ「このはな綺譚」", "OP"]
```

2022-07-11 15:44 UTC, Yesterday17 commented on album/LACM-14697.toml
> +tags = ["ED"]
Seasons?

2022-07-12 02:20 UTC, snylonue commented on album/LACM-14697.toml
> +tags = ["ED"]
什么意思？

2022-07-12 02:55 UTC, Yesterday17 commented on album/LACM-14697.toml
> +tags = ["ED"]
这好像是四季的ED？可以按季把tag打上（？

2022-07-12 03:36 UTC, snylonue commented on album/LACM-14697.toml
> +tags = ["ED"]
只是每三集换一次 ED，不是很必要吧

2022-07-12 03:45 UTC, Yesterday17 approved these changes

2022-07-12 03:45 UTC, Yesterday17 approved these changes
Just need to resolve conflict

2022-07-12 05:30 UTC, merged