fripSide Discs
ProjectAnni/repo pull request #136
Opened 2022-07-23 16:59 UTC by Yesterday17

2022-08-13 16:46 UTC, Last-Order requested changes

2022-08-13 16:46 UTC, Last-Order commented on album/SCFS-0601~2.toml
> +catalog = "SCFS-0601"
```suggestion
title = "nao Side"
catalog = "SCFS-0601"
```

2022-08-13 16:46 UTC, Last-Order commented on album/SCFS-0601~2.toml
> +catalog = "SCFS-0602"
```suggestion
title = "sat Side"
catalog = "SCFS-0602"
```

2022-08-13 16:46 UTC, Last-Order commented on album/SCFS-0801.toml
> +title = "こんいろ∞トキメキ!! ?着せたら脱がさない?"
```suggestion
title = "こんいろ∞トキメキ!! ～着せたら脱がさない～"
```

2022-08-13 16:46 UTC, Last-Order commented on album/SCFS-0901.toml
> +catalog = "SCFS-0901"
跟下面这张有重叠。。
由于这张是Comiket上限定的 我倾向于这张没有分配番号

2022-08-13 16:46 UTC, Last-Order commented on album/SCFS-0901~10.toml
> +artist = "fripSide NAO project!"
```suggestion
artist = "fripSide NAO project!（nao、八木沼悟志）"
```

2022-08-14 08:29 UTC, Yesterday17 commented on album/SCFS-0901.toml
> +catalog = "SCFS-0901"
0-那加一个 @ 变成 `@SCFS-0901`?

2022-08-14 08:32 UTC, Last-Order commented on album/SCFS-0901.toml
> +catalog = "SCFS-0901"
感觉可以起个别的 不然还是有点困惑（

2022-08-14 08:38 UTC, Yesterday17 commented on album/SCFS-0901.toml
> +catalog = "SCFS-0901"
![image](https://user-images.githubusercontent.com/8667822/184529139-a43e1dad-b946-4c96-82ca-ba1fd7684dd7.png)
但他写的就是这个（

2022-08-15 09:17 UTC, Last-Order approved these changes

2022-08-15 10:19 UTC, merged