Mushoku tensei discs
ProjectAnni/repo pull request #145
Opened 2022-09-19 10:10 UTC by SeraphJACK

2022-09-20 11:31 UTC, Yesterday17 requested changes

2022-09-20 11:31 UTC, Yesterday17 commented on album/@MUSHOKU-TENSEI-OST-1.toml
> +catalog = "@MUSHOKU-TENSEI-OST-1"
```suggestion
catalog = "TBR31094D-2"
```

This?
https://vgmdb.net/album/108263

2022-09-20 11:31 UTC, Yesterday17 commented on album/@MUSHOKU-TENSEI-OST-1.toml
> +title = "『無職転生～異世界行ったら本気出す～』 オリジナル・サウンドトラック1"
```suggestion
title = "「無職転生 ～異世界行ったら本気だす～」オリジナル・サウンドトラック1"
```

2022-09-20 11:31 UTC, Yesterday17 commented on album/@MUSHOKU-TENSEI-OST-1.toml
> +title = "『無職転生～異世界行ったら本気出す～』 オリジナル・サウンドトラック1"
怎么标题都会错啊.jpg

2022-09-20 11:31 UTC, Yesterday17 commented on album/@MUSHOKU-TENSEI-OST-1.toml
> +title = "小さい家庭教師\"ロキシー\""
```suggestion
title = '小さい家庭教師"ロキシー"'
```

2022-09-20 11:31 UTC, Yesterday17 commented on album/@MUSHOKU-TENSEI-OST-1.toml
> +title = "オンリー(アコースティックVer.)"
```suggestion
title = "オンリー (アコースティックVer.)"
```

2022-09-20 11:31 UTC, Yesterday17 commented on album/@MUSHOKU-TENSEI-OST-1.toml
> +catalog = "@MUSHOKU-TENSEI-OST-1"
但好像又对不上？

2022-09-20 12:18 UTC, SeraphJACK commented on album/@MUSHOKU-TENSEI-OST-1.toml
> +catalog = "@MUSHOKU-TENSEI-OST-1"
这个是 Special Edition

2022-09-21 05:34 UTC, Yesterday17 commented
有没有 vgmdb 的 diff 看一下（

2022-09-21 05:40 UTC, SeraphJACK commented
https://paste.centos.org/view/ec4e29b4
https://paste.centos.org/view/92efcc50

2022-09-24 02:53 UTC, Yesterday17 approved these changes

2022-09-24 02:53 UTC, merged