酸欠少女
ProjectAnni/repo pull request #146
Opened 2022-09-19 10:39 UTC by SeraphJACK

2022-09-20 11:23 UTC, Yesterday17 commented
3 commits behind master, rebase?

2022-09-20 13:07 UTC, SeraphJACK commented
Fixed

2022-09-20 14:05 UTC, Yesterday17 requested changes

2022-09-20 14:05 UTC, Yesterday17 commented on album/BVCL-1190.toml
> +title = "さユり x MY FIRST STORY - レイメイ"
```suggestion
title = "レイメイ"
```

2022-09-20 16:11 UTC, Last-Order approved these changes

2022-09-24 02:51 UTC, Yesterday17 approved these changes

2022-09-24 02:51 UTC, merged