220917
ProjectAnni/repo pull request #148
Opened 2022-09-26 14:04 UTC by Yesterday17

2022-09-26 16:23 UTC, Last-Order approved these changes

2022-09-26 16:23 UTC, Last-Order commented on album/BRMM-10561.toml
> +tags = ["Morfonica"]
+アニメ「BanG Dream! Morfonication」

2022-09-27 10:31 UTC, SeraphJACK requested changes

2022-09-27 10:31 UTC, SeraphJACK commented on album/ANZX-15302.toml
> +artist = "渡部沙智子"
type = normal

2022-09-27 10:31 UTC, SeraphJACK commented on album/LACA-39911~2.toml
> +catalog = "LACA-39911~2"
edition?

2022-09-27 10:31 UTC, SeraphJACK commented on album/SSCD-0001~2.toml
> +catalog = "SSCD-0001~2"
edition?

2022-09-27 10:34 UTC, Yesterday17 commented on album/ANZX-15302.toml
> +artist = "渡部沙智子"
原来是normal吗（

2022-09-27 10:35 UTC, Yesterday17 commented on album/LACA-39911~2.toml
> +catalog = "LACA-39911~2"
`初回生産限定盤`

2022-09-27 10:35 UTC, Yesterday17 commented on album/SSCD-0001~2.toml
> +catalog = "SSCD-0001~2"
`初回生産限定盤`

2022-09-27 10:36 UTC, Yesterday17 commented on album/LACA-39911~2.toml
> +catalog = "LACA-39911~2"
`初回限定盤`

2022-09-27 14:42 UTC, SeraphJACK approved these changes

2022-09-27 15:21 UTC, merged