Albums/220930
ProjectAnni/repo pull request #149
Opened 2022-09-30 16:04 UTC by Yesterday17

2022-10-13 03:16 UTC, SeraphJACK commented on album/FVCG-1119.toml
> +title = "A.R.／Star-Crossed"
待查

2022-10-13 03:16 UTC, SeraphJACK commented on album/FVCG-1124.toml
> +title = "約束のパラダイム (off Vocal)"
type?

2022-10-13 03:16 UTC, SeraphJACK commented on album/GRE-009.toml
> +title = "STARGATE"
`スターゲイト` ?

2022-10-13 03:39 UTC, Yesterday17 commented on album/GRE-009.toml
> +title = "STARGATE"
看上去应该用 スターゲイト

![](https://media.vgm.io/albums/95/34159/34159-1342638048.jpg)

2022-10-14 12:18 UTC, Last-Order requested changes

2022-10-14 12:18 UTC, Last-Order commented on album/FVCG-1106.toml
> +title = "『STEINS;GATE』OriginalSoundtrack＋ラジオCD(仮)"
辣鸡哦CD去哪里了

2022-10-25 12:35 UTC, Yesterday17 commented on album/FVCG-1119.toml
> +title = "A.R.／Star-Crossed"
いとうかなこ「A.R. / Star-Crossed」

http://steinsgate.jp/goods_16.html

2022-10-25 12:47 UTC, SeraphJACK approved these changes

2022-10-30 07:58 UTC, merged