Deaimon discs
ProjectAnni/repo pull request #151
Opened 2022-10-05 12:05 UTC by SeraphJACK

2022-10-05 12:08 UTC, SeraphJACK commented
https://deaimon.jp/music/

2022-10-12 12:01 UTC, Yesterday17 requested changes

2022-10-12 12:01 UTC, Yesterday17 commented on album/VTZL-200.toml
> +title = "言葉にできない"
TVアニメ「本好きの下剋上 司書になるためには手段を選んでいられません」第3期EDテーマ

2022-10-12 12:01 UTC, Yesterday17 commented on album/VTZL-200.toml
> +title = "言葉にできない"
https://www.jvcmusic.co.jp/flyingdog/-/Discography/A008957/VTZL-200.html

2022-10-12 12:19 UTC, Yesterday17 commented on tag/[Anime] 本好きの下剋上.toml
> +name = "本好きの下剋上"
```suggestion
name = "TVアニメ「本好きの下剋上 司書になるためには手段を選んでいられません」"
```

2022-10-13 02:41 UTC, merged