Yama no susume S1-3 discs
ProjectAnni/repo pull request #155
Opened 2022-10-31 14:03 UTC by SeraphJACK

2022-11-01 03:44 UTC, Yesterday17 commented on tag/[Anime] ヤマノススメ.toml
> +type = "animation"
animation套animation，好怪

2022-11-01 03:45 UTC, Yesterday17 commented on tag/[Anime] ヤマノススメ.toml
> +type = "animation"
最外层把 anime 去掉换成 project 吧

2022-11-01 03:59 UTC, Yesterday17 requested changes
8/15

2022-11-01 03:59 UTC, Yesterday17 commented on album/ESER-002.toml
> +artist = "あおい（井口裕香）、ひなた（阿澄佳奈）"
```suggestion
```

2022-11-01 03:59 UTC, Yesterday17 commented on album/ESER-013.toml
> +artist = "あおい（井口裕香）、ひなた（阿澄佳奈）、かえで（日笠陽子）、ここな（小倉唯）"
```suggestion
```

2022-11-01 03:59 UTC, Yesterday17 commented on album/ESER-015.toml
> +title = '夕暮アフター "虹の橋 ver."'
M-02 - TV Anime "Teekyu Best Selection" Ending Theme Cover

2022-11-01 03:59 UTC, Yesterday17 commented on album/KICM-91526.toml
> +tags = ["TVアニメ「ヤマノススメ セカンドシーズン」", "ED"]
Add tag to instrumental too

2022-11-01 03:59 UTC, Yesterday17 commented on album/SMIB-022CD.toml
> +catalog = "SMIB-022CD"
https://vgmdb.net/album/72458

这个 catalog 哪里来的）

2022-11-01 03:59 UTC, Yesterday17 commented on album/SMIB-022CD.toml
> +artist = "yamazo"
[yamazo](https://vgmdb.net/artist/36118), [Tom-H@ck](https://vgmdb.net/artist/8869)？

2022-11-01 03:59 UTC, Yesterday17 commented on album/SMRR-011.toml
> +artist = "あおい（井口裕香）、ひなた（阿澄佳奈）"
```suggestion
artist = "あおい（井口裕香）、ひなた（阿澄佳奈）"
```

2022-11-01 09:44 UTC, SeraphJACK commented on album/SMIB-022CD.toml
> +catalog = "SMIB-022CD"
> Enclosed with Yama no Susume: Omoide Present Limited Edition Blu-ray (SMIB-022).

2022-11-01 09:45 UTC, SeraphJACK commented on album/SMIB-022CD.toml
> +artist = "yamazo"
这个 vgm 上应该是错的，这里面 track 和后面那一张大 OST 的 disc 3 一样的，所有作曲都是 yamazo

2022-11-01 09:47 UTC, SeraphJACK commented on album/SMRR-011.toml
> +artist = "あおい（井口裕香）、ひなた（阿澄佳奈）"
？

2022-11-01 09:47 UTC, Yesterday17 commented on album/SMIB-022CD.toml
> +catalog = "SMIB-022CD"
但这个只是约定记法吧，按照 repo 的话直接写 BD 的 catalog 就行了

2022-11-01 09:47 UTC, Yesterday17 commented on album/SMRR-011.toml
> +artist = "あおい（井口裕香）、ひなた（阿澄佳奈）"
和 album artist 一样啊，这里不用写

2022-11-01 10:44 UTC, SeraphJACK commented on album/ESER-015.toml
> +title = '夕暮アフター "虹の橋 ver."'
cover 也要加吗？

2022-11-01 10:45 UTC, SeraphJACK commented on album/SMIB-022CD.toml
> +catalog = "SMIB-022CD"
其他 OST 的 catalog 后面带 CD 的，vgm 也是这么收录的（

2022-11-02 09:39 UTC, Yesterday17 commented on album/SMIB-022CD.toml
> +catalog = "SMIB-022CD"
那就这样吧

2022-11-02 09:39 UTC, Yesterday17 commented on album/ESER-015.toml
> +title = '夕暮アフター "虹の橋 ver."'
不用

2022-11-03 12:44 UTC, SeraphJACK commented on album/ESER-015.toml
> +title = '夕暮アフター "虹の橋 ver."'
added

2022-11-06 13:02 UTC, Yesterday17 reviewed
标注了 vgmdb 的是有区别的部分，需要继续查证

2022-11-06 13:02 UTC, Yesterday17 commented on album/SMRR-012.toml
> +title = "あおいと二人で"
```suggestion
title = "ひなたと二人で"
```

vgmdb

2022-11-06 13:02 UTC, Yesterday17 commented on album/SMRR-012.toml
> +title = "人に頼むということ"
```suggestion
title = "人に頼るということ"
```

vgmdb

2022-11-06 13:02 UTC, Yesterday17 commented on album/SMRR-012.toml
> +title = "メインテーマ・想い出の山"
```suggestion
title = "メインテーマ・思い出の山"
```

vgmdb

2022-11-06 13:02 UTC, Yesterday17 commented on album/SMRR-012.toml
> +title = "天の川が見たいの"
```suggestion
title = "天の川がみたいの"
```

vgmdb

2022-11-06 13:08 UTC, Yesterday17 commented on album/SMRR-012.toml
> +title = "あおいと二人で"
![image](https://user-images.githubusercontent.com/8667822/200172504-cf719b57-941a-4f91-9b3f-abb26da93acb.png)

2022-11-06 13:09 UTC, Yesterday17 commented on album/SMRR-012.toml
> +title = "人に頼むということ"
![image](https://user-images.githubusercontent.com/8667822/200172535-1104042d-1c3d-4000-8a77-1b843e14b943.png)

2022-11-06 13:09 UTC, Yesterday17 commented on album/SMRR-012.toml
> +title = "メインテーマ・想い出の山"
![image](https://user-images.githubusercontent.com/8667822/200172556-d0efb68a-ae25-47ba-bca2-ab37c77d6076.png)

2022-11-06 13:10 UTC, Yesterday17 commented on album/SMRR-012.toml
> +title = "天の川が見たいの"
![image](https://user-images.githubusercontent.com/8667822/200172575-1203fefe-a209-4693-ad3e-25ad9c4573c0.png)
这个应该是对的

2022-11-06 13:13 UTC, SeraphJACK commented on album/EAAB-017CD.toml
> +[album]
artist 是我手抄 vgm 的

2022-11-06 13:13 UTC, SeraphJACK commented on album/EAAB-016CD.toml
> +[album]
artist 是我手抄 vgm 的

2022-11-06 13:13 UTC, Yesterday17 approved these changes

2022-11-06 13:15 UTC, merged