蒼の彼方のフォーリズム Discs
ProjectAnni/repo pull request #167
Opened 2022-12-18 09:40 UTC by Yesterday17

2023-02-10 06:03 UTC, SeraphJACK requested changes

2023-02-10 06:04 UTC, Yesterday17 commented on album/BRMM-10547.toml
> +type = "normal"
有人声的，livecd

2023-02-10 15:36 UTC, Yesterday17 commented on album/MVC-0064.toml
> +[[discs.tracks]]
哦，那我这个就不是这张，删了吧）

2023-02-18 16:45 UTC, Yesterday17 commented on album/BRMM-10547.toml
> +tags = ["少女☆歌劇 レヴュースタァライト -The LIVE-"]
NO, Live CD

2023-02-19 02:11 UTC, SeraphJACK approved these changes

2023-02-19 02:11 UTC, merged