Albums/230111
ProjectAnni/repo pull request #173
Opened 2023-01-10 18:42 UTC by Yesterday17

2023-01-13 06:28 UTC, tuzi3040 requested changes

2023-01-13 06:28 UTC, tuzi3040 commented on album/COZC-1777.toml
> +type = "instrumental"
```suggestion
title = "Elder flower (Instrumental)"
tags = ["精霊幻想記", "ED"]
type = "instrumental"
```

2023-01-13 06:28 UTC, tuzi3040 commented on album/DMCS-00018.toml
> +tags = ["愛美"]
好怪哦

2023-01-13 06:28 UTC, tuzi3040 commented on album/COCC-18056.toml
> +type = "drama"
```suggestion
title = "Dramatic!"
```

2023-01-13 13:59 UTC, Yesterday17 commented on album/DMCS-00018.toml
> +tags = ["愛美"]
哪里怪了）

2023-01-15 04:00 UTC, tuzi3040 approved these changes

2023-01-15 04:00 UTC, merged