Blue archive
ProjectAnni/repo pull request #175
Opened 2023-01-23 12:25 UTC by snylonue

2023-01-23 13:23 UTC, Yesterday17 requested changes

2023-01-23 13:23 UTC, Yesterday17 commented on album/BACD-0001.toml
> +title = "Blue Archive Original Soundtrack Vol. 1 ~Longing for the memorable days~"
```suggestion
title = "Blue Archive Original Soundtrack Vol.1 ~Longing for the memorable days~"
```

2023-01-23 13:23 UTC, Yesterday17 commented on album/KICM-2078.toml
> +[album]
https://github.com/ProjectAnni/repo/blob/master/album/KICM-92078.toml

Any difference?

2023-01-23 14:15 UTC, snylonue commented on album/KICM-2078.toml
> +[album]
No. Removed.

2023-01-25 04:10 UTC, Yesterday17 approved these changes

2023-01-25 04:12 UTC, merged