Shuumatsu Nani Shitemasu ka discs
ProjectAnni/repo pull request #177
Opened 2023-02-15 04:07 UTC by SeraphJACK

2023-02-15 04:11 UTC, Yesterday17 approved these changes
具体内容没看，能和 vgmdb 对上就行（

2023-02-15 04:11 UTC, Yesterday17 commented on album/LACM-14589.toml
> +tags = ["animation:終末なにしてますか？"]
animation 标签打曲上，另外，非 anime 盘的那几张也处理一下吧（

2023-02-15 04:11 UTC, Yesterday17 commented on album/LACM-14607.toml
> +tags = ["animation:終末なにしてますか？"]
同上

2023-02-15 04:11 UTC, Yesterday17 commented on tag/default.toml
> +name = "終末なにしてますか？"
```suggestion
name = "終末なにしてますか？ 忙しいですか？ 救ってもらっていいですか？"
```

2023-02-15 04:11 UTC, Yesterday17 commented on tag/default.toml
> +names.zh-hans = "末日时在做什么？"
同上，中文全名

2023-02-15 04:11 UTC, Yesterday17 commented on album/LACA-9522~3.toml
> +catalog = "LACA-9522~3"
```suggestion
catalog = "LACA-9522"
```

2023-02-15 04:11 UTC, Yesterday17 commented on album/LACA-9522~3.toml
> +title = "TVアニメ『終末なにしてますか？ 忙しいですか？ 救ってもらっていいですか？』オリジナルサウンドトラック「青い記憶」"
title 是不是可以省略

2023-02-15 04:11 UTC, Yesterday17 commented on album/LACA-9522~3.toml
> +title = "TVアニメ『終末なにしてますか？ 忙しいですか？ 救ってもらっていいですか？』オリジナルサウンドトラック「青い記憶」"
同上

2023-02-15 04:11 UTC, Yesterday17 commented on album/LACA-9522~3.toml
> +catalog = "LACA-9522~3"
```suggestion
catalog = "LACA-9523"
```

2023-02-15 04:11 UTC, Yesterday17 commented
点错了，不是 approve 🤔

2023-02-15 04:14 UTC, Yesterday17 requested changes

2023-02-15 04:14 UTC, Yesterday17 commented on album/LACA-9522~3.toml
> +album_id = "c0b2df96-fa6d-4a08-a556-9b6456d820ea"
1

2023-02-15 04:14 UTC, SeraphJACK commented on album/LACA-9522~3.toml
> +title = "TVアニメ『終末なにしてますか？ 忙しいですか？ 救ってもらっていいですか？』オリジナルサウンドトラック「青い記憶」"
但是 album title 确实是这个，其实我想直接写 青い記憶 （

2023-02-15 05:05 UTC, Yesterday17 requested changes

2023-02-15 05:05 UTC, Yesterday17 commented on album/LACA-9522~3.toml
> +title = "TVアニメ『終末なにしてますか？ 忙しいですか？ 救ってもらっていいですか？』オリジナルサウンドトラック「青い記憶」"
我是说 disc title 是不是可以省略）

2023-02-15 05:05 UTC, Yesterday17 commented on album/LACA-9522~3.toml
> +artist = "Variours Artists"
```suggestion
artist = "Various Artists"
```

2023-02-15 05:05 UTC, Yesterday17 commented on album/LACM-14588.toml
> +tags = ["animation:終末なにしてますか？忙しいですか？救ってもらっていいですか？"]
OP?

2023-02-15 05:05 UTC, Yesterday17 commented on album/LACM-14589.toml
> +tags = []
"田所あずさ"

2023-02-15 05:05 UTC, Yesterday17 commented on album/LACM-14607.toml
> +tags = ["animation:終末なにしてますか？忙しいですか？救ってもらっていいですか？", "artist:TRUE", "ED"]
ED 和 animation 打到 track 上？

2023-02-15 05:07 UTC, SeraphJACK commented on album/LACM-14607.toml
> +tags = ["animation:終末なにしてますか？忙しいですか？救ってもらっていいですか？", "artist:TRUE", "ED"]
所以 track 都是 ED （

2023-02-15 05:09 UTC, SeraphJACK commented on album/LACA-9522~3.toml
> +title = "TVアニメ『終末なにしてますか？ 忙しいですか？ 救ってもらっていいですか？』オリジナルサウンドトラック「青い記憶」"
省略成什么（

2023-02-16 03:15 UTC, Yesterday17 commented on album/LACM-14588.toml
> +tags = ["animation:終末なにしてますか？忙しいですか？救ってもらっていいですか？", "OP"]
这张上补一个 `edition = "アーティストジャケット盤"`

2023-02-16 03:17 UTC, SeraphJACK commented on album/LACM-14588.toml
> +tags = ["animation:終末なにしてますか？忙しいですか？救ってもらっていいですか？", "OP"]
？这张不是啊

2023-02-16 03:26 UTC, Yesterday17 approved these changes

2023-02-16 03:26 UTC, merged