add some discs
ProjectAnni/repo pull request #182
Opened 2023-03-18 06:50 UTC by Last-Order

2023-04-08 04:04 UTC, Yesterday17 requested changes

2023-04-08 04:04 UTC, Yesterday17 commented on album/SMCL-814.toml
> +title = "シスXラブ"
```suggestion
title = "シス×ラブ"
```

2023-04-08 04:04 UTC, Yesterday17 commented on album/SMCL-814.toml
> +artist = "HoneyWorks（成海聖奈（雨宮天）、成海萌奈（夏川椎菜））"
```suggestion
artist = "成海聖奈（雨宮天）、成海萌奈（夏川椎菜）"
```

2023-04-08 04:04 UTC, Yesterday17 commented on album/SMCL-814.toml
> +artist = "HoneyWorks（濱中翠（Gero））"
```suggestion
artist = "濱中翠（Gero）"
```

2023-04-08 04:04 UTC, Yesterday17 commented on album/SMCL-814.toml
> +artist = "HoneyWorks（成海聖奈（雨宮天））"
```suggestion
artist = "成海聖奈（雨宮天）"
```

2023-04-08 04:04 UTC, Yesterday17 commented on album/SMCL-814.toml
> +artist = "HoneyWorks（成海聖奈（雨宮天））"
```suggestion
artist = "成海聖奈（雨宮天）"
```

2023-04-08 04:04 UTC, Yesterday17 commented on album/SMCL-814.toml
> +artist = "HoneyWorks（成海聖奈（雨宮天））"
```suggestion
artist = "成海聖奈（雨宮天）"
```

2023-04-08 04:04 UTC, Yesterday17 commented on album/SMCL-814.toml
> +artist = "HoneyWorks（瀬戸口雛（麻倉もも））"
```suggestion
artist = "瀬戸口雛（麻倉もも）"
```

2023-04-08 04:04 UTC, Yesterday17 commented on album/SMCL-814.toml
> +artist = "HoneyWorks（榎本虎太朗（花江夏樹）、綾瀬恋雪（堀江瞬））"
```suggestion
artist = "榎本虎太朗（花江夏樹）、綾瀬恋雪（堀江瞬）"
```

2023-04-08 04:04 UTC, Yesterday17 commented on album/SMCL-814.toml
> +artist = "HoneyWorks（高見沢アリサ（東山奈央））"
```suggestion
artist = "高見沢アリサ（東山奈央）"
```

2023-04-08 04:04 UTC, Yesterday17 commented on album/SMCL-814.toml
> +title = "男の子の目的は何?"
```suggestion
title = "男の子の目的は何？"
```

2023-04-08 04:04 UTC, Yesterday17 commented on album/SMCL-814.toml
> +title = "女の子の愛って何?"
```suggestion
title = "女の子の愛って何？"
```

2023-04-08 04:04 UTC, Yesterday17 commented on album/SMCL-814.toml
> +artist = "HoneyWorks（山本幸大（松岡禎丞））"
```suggestion
artist = "山本幸大（松岡禎丞）"
```

2023-04-08 04:04 UTC, Yesterday17 commented on album/SMCL-814.toml
> +artist = "HoneyWorks（明智咲（緑川光））"
```suggestion
artist = "明智咲（緑川光）"
```

2023-04-08 04:32 UTC, Last-Order commented on album/DHAC-D789.toml
> +catalog = "DHAC-D789"
![image](https://user-images.githubusercontent.com/3362825/230703214-1c277f38-cf9e-453a-8ec9-3564545087db.png)
mora的，edition也写的mora（我没有实体

2023-04-08 04:44 UTC, Yesterday17 requested changes

2023-04-08 04:44 UTC, Yesterday17 commented on album/LACM-24150.toml
> +title = "未来は風のように"
```suggestion
title = "未来は風のように"
tags = ["ED"]
```

2023-04-08 04:44 UTC, Yesterday17 commented on album/LACM-24150.toml
> +type = "instrumental"
```suggestion
type = "instrumental"
tags = ["ED"]
```

2023-04-17 17:13 UTC, Yesterday17 approved these changes

2023-04-17 17:14 UTC, merged