2023 summer
ProjectAnni/repo pull request #202
Opened 2023-08-22 07:50 UTC by snylonue

2023-08-22 10:21 UTC, Yesterday17 commented on album/@Mushoku-Tensei-02.toml
> +catalog = "@Mushoku-Tensei-02"
参考一下 https://mora.jp/package/43000033/PA00118842-0-1/?trackMaterialNo=24212188？

2023-08-22 10:21 UTC, Yesterday17 commented on album/LZC-2436.toml
> +artist = "ARCANA PROJECT"
members

2023-08-22 10:21 UTC, Yesterday17 commented on album/LZC-2436.toml
> +title = "ユリイカ"
这张现在是先行配信吗，有对应的单曲/专辑吗

2023-08-22 12:27 UTC, snylonue commented on album/LZC-2436.toml
> +title = "ユリイカ"
没主意，换了

2023-08-22 12:28 UTC, snylonue commented on album/@Mushoku-Tensei-02.toml
> +catalog = "@Mushoku-Tensei-02"
catalog 吗？还是没找到（

2023-08-23 02:46 UTC, Yesterday17 commented on album/@Mushoku-Tensei-02.toml
> +catalog = "@Mushoku-Tensei-02"
看看 PA00118842 能不能用）

2023-08-23 02:48 UTC, Yesterday17 commented on album/@Mushoku-Tensei-02.toml
> +catalog = "@Mushoku-Tensei-02"
算了，维持这样吧，之后要考虑一下配信限定没有 catalog 的处理方案了

2023-08-23 02:50 UTC, Yesterday17 requested changes

2023-08-23 02:50 UTC, Yesterday17 commented on album/@Mushoku-Tensei-02.toml
> +tags = ["無職転生 ～異世界行ったら本気だす～ 第2期", "ED"]
/tag +大原ゆい子

2023-08-23 02:50 UTC, Yesterday17 commented on album/@Mushoku-Tensei-03.toml
> +tags = ["無職転生 ～異世界行ったら本気だす～ 第2期", "ED"]
/tag +大原ゆい子

2023-08-28 03:10 UTC, Yesterday17 requested changes

2023-08-28 03:10 UTC, Yesterday17 commented on album/LACM-24416.toml
> +tags = ["SYNDUALITY Noir"]
/tag add ARCANA PROJECT

2023-08-28 03:10 UTC, Yesterday17 commented on album/LACM-24416.toml
> +tags = ["SYNDUALITY Noir"]
"SYNDUALITY Noir" 的 tag 打到 "ユリイカ" 上吧

2023-08-28 03:48 UTC, Yesterday17 approved these changes

2023-08-28 03:49 UTC, merged