十三機兵防衛圏 disc
ProjectAnni/repo pull request #204
Opened 2023-10-29 05:17 UTC by snylonue

2023-10-30 03:40 UTC, Yesterday17 requested changes

2023-10-30 03:40 UTC, Yesterday17 commented on album/BSPE-1091~4.toml
> +tags = ["十三機兵防衛圏"]
OST tag

2023-10-30 04:37 UTC, snylonue commented on album/BSPE-1091~4.toml
> +tags = ["十三機兵防衛圏"]
Added

2023-10-31 12:40 UTC, tuzi3040 approved these changes

2023-12-29 16:02 UTC, Yesterday17 approved these changes

2023-12-29 16:02 UTC, merged