add: Blue Archive OST vol.5 metadata
ProjectAnni/repo pull request #207
Opened 2024-02-26 15:56 UTC by LacLic

2024-02-26 15:58 UTC, SeraphJACK commented
`[WARN][album/BACD-0013~4.toml] 0:0: Duplicate catalog BACD-0013~4`

2024-02-26 16:01 UTC, SeraphJACK requested changes

2024-02-26 16:01 UTC, SeraphJACK commented on album/BACD-0013~4.toml
> +catalog = "BACD-0013~4"
```suggestion
catalog = "@BACD-0013-1~2"
```

2024-02-26 16:01 UTC, SeraphJACK commented on album/BACD-0013~4.toml
> +catalog = "BACD-0013~4"
```suggestion
catalog = "@BACD-0013-1"
```

2024-02-26 16:01 UTC, SeraphJACK commented on album/BACD-0013~4.toml
> +catalog = "BACD-0013~4"
```suggestion
catalog = "@BACD-0013-2"
```

2024-02-26 16:04 UTC, SeraphJACK requested changes

2024-02-26 16:04 UTC, SeraphJACK commented on album/BACD-0013~4.toml
> +type = "normal"
纯音乐应该是 `absolute`

2024-02-26 16:32 UTC, LacLic commented
在新的 commit 中进行了修改

2024-02-27 02:59 UTC, SeraphJACK approved these changes

2024-02-27 02:59 UTC, merged