平行四界Quadimension Discs
ProjectAnni/repo pull request #44
Opened 2021-11-23 14:35 UTC by Yesterday17

2021-12-03 18:57 UTC, tuzi3040 requested changes

2021-12-03 18:57 UTC, tuzi3040 commented on album/QMEP-0002.toml
> +tags = ["洛天依", "乐正绫", "星尘", "平行四界 EP"]
```suggestion
tags = ["洛天依", "乐正绫", "星尘", "平行四界", "EP"]
```
May be better to add a single independent tag named `EP`, and also `album` and so on.

2021-12-03 18:57 UTC, tuzi3040 commented on tag/[AAAA] 平行四界Quadimension.toml
> +  "平行四界 EP",
```suggestion
  "平行四界",
```

2021-12-04 03:53 UTC, Yesterday17 commented on album/QMEP-0002.toml
> +tags = ["洛天依", "乐正绫", "星尘", "平行四界 EP"]
Making `EP`/`Single`/`Album` a single category might be strange. Something like `平行四界:default` might be better for those albums(without series).

2021-12-04 05:19 UTC, tuzi3040 commented on album/QMEP-0002.toml
> +tags = ["洛天依", "乐正绫", "星尘", "平行四界 EP"]
Or `平行四界:EP`.

2021-12-08 05:24 UTC, Yesterday17 commented on album/QMEP-0002.toml
> +tags = ["洛天依", "乐正绫", "星尘", "平行四界 EP"]
`平行四界:EP` Seems good.

2021-12-17 11:46 UTC, tuzi3040 approved these changes

2021-12-17 11:54 UTC, merged