[WIP] add lovelive discs
ProjectAnni/repo pull request #76
Opened 2022-03-30 11:21 UTC by Last-Order

2022-03-30 14:59 UTC, tuzi3040 requested changes

2022-03-30 14:59 UTC, tuzi3040 commented on album/LACM-14415.toml
> +[[discs.tracks]]
Probably wrong order.

2022-03-30 15:34 UTC, Yesterday17 requested changes
25/76

2022-03-30 15:34 UTC, Yesterday17 commented on album/BCXA-0702.toml
> +artist = "絢瀬絵里（南條愛乃）・東條希（楠田亜衣奈）"
```suggestion
artist = "絢瀬絵里（南條愛乃）、東條希（楠田亜衣奈）"
```

2022-03-30 15:34 UTC, Yesterday17 commented on album/BCXA-0697.toml
> +title = "夢なき夢は夢じゃない(Off Vocal)"
```suggestion
title = "夢なき夢は夢じゃない (Off Vocal)"
```

2022-03-30 15:34 UTC, Yesterday17 commented on album/BCXA-0698.toml
> +title = "Anemone heart(Off Vocal)"
```suggestion
title = "Anemone heart (Off Vocal)"
```

2022-03-30 15:34 UTC, Yesterday17 commented on album/BCXA-0701.toml
> +title = "にこぷり♡女子道（Off Vocal）"
```suggestion
title = "にこぷり♡女子道 (Off Vocal)"
```

2022-03-30 15:34 UTC, Yesterday17 commented on album/BCXA-0702.toml
> +title = "硝子の花園（Off Vocal）"
```suggestion
title = "硝子の花園 (Off Vocal)"
```

2022-03-30 15:34 UTC, Yesterday17 commented on album/BEPC-0013.toml
> +title = "同じ星が見たい(Off Vocal)"
```suggestion
title = "同じ星が見たい (Off Vocal)"
```

2022-03-30 15:34 UTC, Yesterday17 commented on album/LACA-15169.toml
> +title = "ラブライブ！ Solo Live! from μ's 南ことり ことりLovin' you"
```suggestion
title = "ラブライブ！Solo Live! from μ's 南ことり ことりLovin' you"
```

同理（

2022-03-30 15:34 UTC, Yesterday17 commented on album/LACA-15498.toml
> +title = "Notes of School Idol Days ～Curtain Call～"
```suggestion
title = "劇場版『ラブライブ! The School Idol Movie』オリジナルサウンドトラック Notes of School Idol Days ～Curtain Call～"
```
加一下更好区分 OST 吧

2022-03-30 15:34 UTC, Yesterday17 commented on album/LACA-39260~1.toml
> +title = "ぶる～べりぃとれいん"
```suggestion
title = "ぶる～べりぃ とれいん"
```

这里有没有空格还需要检查一下，VGMdb 上直接是 `ぶる～べりぃ□とれいん`，验证之后可以改一下（

2022-03-30 16:26 UTC, Yesterday17 requested changes
28/76

2022-03-30 16:26 UTC, Yesterday17 commented on album/LACA-9281~2.toml
> +title = "Wonder zone(TVサイズ)[第9話挿入歌]"
```suggestion
title = "Wonder zone (TVサイズ)"
```

2022-03-30 16:26 UTC, Yesterday17 commented on album/LACA-9281~2.toml
> +title = "きっと青春が聞こえる(TVサイズ・ことりソロ)[第9話エンディングテーマ]"
```suggestion
title = "きっと青春が聞こえる  (TVサイズ・ことりソロ)"
```

2022-03-30 16:26 UTC, Yesterday17 commented on album/LACA-9281~2.toml
> +title = "No brand girls(TVサイズ)[第11話挿入歌]"
```suggestion
title = "No brand girls (TVサイズ)"
```

2022-03-30 16:26 UTC, Yesterday17 commented on album/LACA-9281~2.toml
> +title = "きっと青春が聞こえる(TVサイズ・穂乃果ソロ)[第12話挿入歌]"
```suggestion
title = "きっと青春が聞こえる (TVサイズ・穂乃果ソロ)"
```

2022-03-30 16:26 UTC, Yesterday17 commented on album/LACA-9281~2.toml
> +title = "START：DASH!!(TVサイズ)[第13話挿入歌]"
```suggestion
title = "START：DASH!! (TVサイズ)"
```

2022-03-30 16:26 UTC, Yesterday17 commented on album/LACA-9281~2.toml
> +title = "きっと青春が聞こえる(TVサイズ)[第3・8・10・11・13話エンディングテーマ]"
```suggestion
title = "きっと青春が聞こえる (TVサイズ)"
```

2022-03-30 16:26 UTC, Yesterday17 commented on album/LACA-9281~2.toml
> +[album]
这张里有很多表示出现位置的 `[xxx]`，但有些没有，比如 `Private Wars[第1話挿入歌]`

在想是不是可以加一个 comment 字段放这种东西

https://www.lantis.jp/release-item/LACA-9281.html

2022-03-31 03:17 UTC, Last-Order commented on album/LACA-9281~2.toml
> +artist = "高坂穂乃果（新田恵海）、南ことり（内田彩）、園田海未（三森すずこ）、星空凛（飯田里穂）、西木野真姫（Pile）、小泉花陽（久保ユリカ）、矢澤にこ（徳井青空）"
这个跟官网一致的

2022-03-31 05:27 UTC, Yesterday17 requested changes
44/75

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +tags = ["μ's"]
动画 Tag

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "これまでのラブライブ！ ～ミュージカルver.～"
```suggestion
title = "これまでのラブライブ！ ～ミュージカルver.～ [第1話挿入歌]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "どんなときもずっと (TVサイズ・のぞえりにこ)"
```suggestion
title = "どんなときもずっと (TVサイズ・のぞえりにこ) [第2話エンディングテーマ]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "Shocking Party"
```suggestion
title = "Shocking Party [第3話挿入歌]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "ユメノトビラ (TVサイズ)"
```suggestion
title = "ユメノトビラ (TVサイズ) [第3話挿入歌]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "どんなときもずっと (TVサイズ)"
```suggestion
title = "どんなときもずっと (TVサイズ) [第3話エンディングテーマ]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "どんなときもずっと (TVサイズ・にこソロ)"
```suggestion
title = "どんなときもずっと (TVサイズ・にこソロ) [第4話エンディングテーマ]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "Love wing bell (TVサイズ)"
```suggestion
title = "Love wing bell (TVサイズ) [第5話挿入歌]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "どんなときもずっと (TVサイズ・凛ソロ)"
```suggestion
title = "どんなときもずっと (TVサイズ・凛ソロ) [第5話エンディングテーマ]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "Dancing stars on me! (TVサイズ)"
```suggestion
title = "Dancing stars on me! (TVサイズ) [第6話挿入歌]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "どんなときもずっと (TVサイズ・まきりんぱな)"
```suggestion
title = "どんなときもずっと (TVサイズ・まきりんぱな) [第6話エンディングテーマ]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "どんなときもずっと (TVサイズ・ことほのうみ)"
```suggestion
title = "どんなときもずっと (TVサイズ・ことほのうみ) [第7話エンディングテーマ]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "どんなときもずっと (TVサイズ・のぞまきえり)"
```suggestion
title = "どんなときもずっと (TVサイズ・のぞまきえり) [第8話エンディングテーマ]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "Snow halation (TVサイズ)"
```suggestion
title = "Snow halation (TVサイズ) [第9話挿入歌]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "どんなときもずっと (TVサイズ・穂乃果ソロ)"
```suggestion
title = "どんなときもずっと (TVサイズ・穂乃果ソロ) [第10話エンディングテーマ]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "どんなときもずっと (TVサイズ・全員合唱)"
```suggestion
title = "どんなときもずっと (TVサイズ・全員合唱) [第11話エンディングテーマ]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "KiRa-KiRa Sensation! (TVサイズ)"
```suggestion
title = "KiRa-KiRa Sensation! (TVサイズ) [第12話挿入歌]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "僕らは今のなかで (TVサイズ)"
```suggestion
title = "僕らは今のなかで (TVサイズ) [第12話アンコール]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "愛してるばんざーい！ (Piano Mix)"
```suggestion
title = "愛してるばんざーい！ (Piano Mix) [第13話挿入歌]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "Oh,Love&Peace! (TVサイズ)"
```suggestion
title = "Oh,Love&Peace! (TVサイズ) [第13話挿入歌]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "Happy maker! (TVサイズ)"
```suggestion
title = "Happy maker! (TVサイズ) [第13話挿入歌]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +title = "Shocking Party (TVサイズ)"
```suggestion
title = "Shocking Party (TVサイズ) [第3話挿入歌]"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACA-9356~7.toml
> +artist = "A-RISE（綺羅ツバサ（桜川めぐ）、統堂英玲奈（松永真穂）、優木あんじゅ（大橋歩夕））"
```suggestion
artist = "A-RISE（綺羅ツバサ（桜川めぐ）、統堂英玲奈（松永真穂）、優木あんじゅ（大橋歩夕））"
type = "normal"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14054.toml
> +title = "きっと青春が聞こえる(Off Vocal)"
```suggestion
title = "きっと青春が聞こえる (Off Vocal)"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14054.toml
> +title = "輝夜の城で踊りたい(Off Vocal)"
```suggestion
title = "輝夜の城で踊りたい (Off Vocal)"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-4774.toml
> +artist = "星空 凛（飯田里穂）"
```suggestion
artist = "星空凛（飯田里穂）"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14069.toml
> +title = "No brand girls(Off Vocal)"
```suggestion
title = "No brand girls (Off Vocal)"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14069.toml
> +title = "START：DASH!!(Off Vocal)"
```suggestion
title = "START：DASH!! (Off Vocal)"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14101.toml
> +title = "プールでトレーニング！？ (ミニドラマ)"
```suggestion
title = "プールでトレーニング！？"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14102.toml
> +title = "プールでウェイトレス！？ (ミニドラマ)"
```suggestion
title = "プールでウェイトレス！？"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14103.toml
> +title = "プールでオンステージ！ (ミニドラマ)"
```suggestion
title = "プールでオンステージ！"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14220.toml
> +title = "それは僕たちの奇跡(Off Vocal)"
```suggestion
title = "それは僕たちの奇跡 (Off Vocal)"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14220.toml
> +title = "だってだって噫無情(Off Vocal)"
```suggestion
title = "だってだって噫無情 (Off Vocal)"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14230.toml
> +title = "どんなときもずっと(Off Vocal)"
```suggestion
title = "どんなときもずっと (Off Vocal)"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14230.toml
> +title = "COLORFUL VOICE(Off Vocal)"
```suggestion
title = "COLORFUL VOICE (Off Vocal)"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14241.toml
> +title = "ユメノトビラ（Off Vocal）"
```suggestion
title = "ユメノトビラ (Off Vocal)"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14241.toml
> +title = "SENTIMENTAL StepS（Off Vocal）"
```suggestion
title = "SENTIMENTAL StepS (Off Vocal)"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14242.toml
> +title = "Love wing bell／Dancing stars on me!"
要不要考虑用 VGMdb 的这个
```suggestion
title = "Love wing bell☆Dancing stars on me!"
```
来源：https://vgmdb.net/db/covers.php?do=view&cover=198730

官网：https://www.lantis.jp/release-item/LACM-14242.html
![image](https://user-images.githubusercontent.com/8667822/160982671-6d54b165-798d-492d-82fc-946e735b9f7e.png)

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14242.toml
> +title = "Love wing bell(Off Vocal)"
```suggestion
title = "Love wing bell (Off Vocal)"
```

2022-03-31 05:27 UTC, Yesterday17 commented on album/LACM-14242.toml
> +title = "Dancing stars on me!(Off Vocal)"
```suggestion
title = "Dancing stars on me! (Off Vocal)"
```

2022-03-31 16:15 UTC, Last-Order commented on album/LACM-14242.toml
> +title = "Love wing bell／Dancing stars on me!"
封面标题艺术化表现 这个还是用/吧 跟其他保持一致

2022-04-01 13:37 UTC, Yesterday17 requested changes
75/75

2022-04-01 13:37 UTC, Yesterday17 commented on album/LACM-14415.toml
> +[album]
这张的顺序对吗，附 VGMdb 的输出结果：

```toml
[album]
album_id = "8ab5794d-9deb-4ebb-a4d8-852222be74e8"
title = "錯覚CROSSROADS / BiBi"
artist = ""
date = 2016-01-20
type = "normal"
catalog = "LACM-14415"
tags = []

[[discs]]
title = "Disc 1"
catalog = "LACM-14415"

[[discs.tracks]]
title = "錯覚CROSSROADS"

[[discs.tracks]]
title = "PSYCHIC FIRE"

[[discs.tracks]]
title = "錯覚CROSSROADS(Off Vocal)"

[[discs.tracks]]
title = "PSYCHIC FIRE(Off Vocal)"
```

2022-04-01 13:37 UTC, Yesterday17 commented on album/LACM-14950.toml
> +title = "A song for You！ You？ You！！"
```suggestion
title = "A song for You！You？You！！"
```

2022-04-01 13:37 UTC, Yesterday17 commented on album/LACM-14950.toml
> +title = "A song for You！ You？ You！！"
```suggestion
title = "A song for You！You？You！！"
```

2022-04-01 13:37 UTC, Yesterday17 commented on album/LACM-14950.toml
> +title = "A song for You！ You？ You！！(Off Vocal)"
```suggestion
title = "A song for You！You？You！！(Off Vocal)"
```

2022-04-01 13:37 UTC, Yesterday17 commented on album/LACM-34155.toml
> +title = "危ない！？ イン・マイ・ドリーム"
```suggestion
title = "危ない！？イン・マイ・ドリーム"
```

2022-04-01 13:37 UTC, Yesterday17 commented on album/LACM-4738.toml
> +artist = "μ's（高坂穂乃果（新田恵海）、絢瀬絵里（南條愛乃）、南ことり（内田彩）、園田海未（三森すずこ）、星空凛（飯田里穂）、西木野真姫（Pile）、東條希（楠田亜衣奈）、小泉花陽（久保ユリカ）、矢澤にこ（徳井青空））"
artist 可以省略，下同

2022-04-01 13:37 UTC, Yesterday17 commented on album/LACM-4812.toml
> +date = 2011-03-25
```suggestion
date = 2011-05-25
```

https://www.lantis.jp/release-item/LACM-4812.html

2022-04-01 13:37 UTC, Yesterday17 commented on album/LZM-2057~62.toml
> +title = "あ・の・ね・が・ん・ば・れ！ (NOZOMI Mix)"
```suggestion
title = "あ・の・ね・が・ん・ば・れ！(NOZOMI Mix)"
```

2022-04-01 13:37 UTC, Yesterday17 commented on album/LZM-2057~62.toml
> +title = "ラブライブ！ Solo Live! from μ's 東條希 ノゾミ♪カナエテ"
```suggestion
title = "ラブライブ！Solo Live! from μ's 東條希 ノゾミ♪カナエテ"
```

2022-04-01 13:37 UTC, Yesterday17 commented on album/LZM-2057~62.toml
> +title = "Solo Live! collection Memorial BOX I"
```suggestion
title = "ラブライブ！μ's Memorial BOX I Solo Live! Collection"
```

2022-04-01 13:37 UTC, Yesterday17 commented on album/LZM-2057~62.toml
> +title = "ラブライブ！ Solo Live! from μ's 矢澤にこ スマイル・フォー・ユー"
```suggestion
title = "ラブライブ！Solo Live! from μ's 矢澤にこ スマイル・フォー・ユー"
```

2022-04-01 13:37 UTC, Yesterday17 commented on album/LZM-2057~62.toml
> +title = "ラブライブ！ Solo Live! from μ's 西木野真姫 TRUE DIVA"
```suggestion
title = "ラブライブ！Solo Live! from μ's 西木野真姫 TRUE DIVA"
```

2022-04-01 13:37 UTC, Yesterday17 commented on album/LZM-2057~62.toml
> +title = "ラブライブ！ Solo Live! from μ's 絢瀬絵里 Beloved Ellie"
```suggestion
title = "ラブライブ！Solo Live! from μ's 絢瀬絵里 Beloved Ellie"
```

2022-04-01 13:37 UTC, Yesterday17 commented on album/LZM-2057~62.toml
> +title = "ラブライブ！ Solo Live! from μ's 星空凛 THE BRILLIANT STAR☆"
```suggestion
title = "ラブライブ！Solo Live! from μ's 星空凛 THE BRILLIANT STAR☆"
```

2022-04-01 13:37 UTC, Yesterday17 commented on album/LZM-2057~62.toml
> +title = "ラブライブ！ Solo Live! from μ's 小泉花陽 あなただけの太陽になりたい"
```suggestion
title = "ラブライブ！Solo Live! from μ's 小泉花陽 あなただけの太陽になりたい"
```

2022-04-01 16:01 UTC, Yesterday17 requested changes

2022-04-01 16:01 UTC, Yesterday17 commented on album/LACM-14415.toml
> +title = "PSYCHIC FIRE"
怎么后面两个顺序调了前面两个没变）

2022-04-04 10:41 UTC, Yesterday17 requested changes

2022-04-04 10:41 UTC, Yesterday17 commented on tag/[AAAA] ラブライブ!シリーズ.toml
> +name = "ラブライブ!シリーズ"
```suggestion
name = "ラブライブ!シリーズ"
type = "project"
```

2022-04-04 10:41 UTC, Yesterday17 commented on tag/[AAAA] ラブライブ!シリーズ.toml
> +name = "ラブライブ!"
```suggestion
name = "ラブライブ!"
type = "project"
```

2022-04-04 10:41 UTC, Yesterday17 commented on tag/[AAAA] ラブライブ!シリーズ.toml
> +    "TVアニメ「ラブライブ！」",
includes.animation = [xxx]

2022-04-04 10:41 UTC, Yesterday17 commented on tag/[AAAA] ラブライブ!シリーズ.toml
> +    # μ's（高坂穂乃果（新田恵海）、絢瀬絵里（南條愛乃）、南ことり（内田彩）、園田海未（三森すずこ）、星空凛（飯田里穂）、西木野真姫（Pile）、東條希（楠田亜衣奈）、小泉花陽（久保ユリカ）、矢澤にこ（徳井青空））
includes.group = [xxx]

2022-04-05 16:00 UTC, Yesterday17 approved these changes

2022-04-06 07:26 UTC, merged