虹ヶ咲学園スクールアイドル同好会 第一季
ProjectAnni/repo pull request #82
Opened 2022-04-08 09:36 UTC by Last-Order

2022-04-08 11:41 UTC, tuzi3040 approved these changes
Time to add some `category` tags.

2022-04-08 16:26 UTC, Yesterday17 requested changes

2022-04-08 16:26 UTC, Yesterday17 commented on tag/[AAAA] ラブライブ!シリーズ.toml
> +include-by = "ラブライブ!シリーズ"
anni 的问题，应该是 `included-by`，下同

等构建完再跑一次 test

2022-04-08 16:26 UTC, Yesterday17 commented on album/LACM-24061.toml
> +    "虹ヶ咲学園スクールアイドル同好会",
加了 child tag 就不用加 parent 了，其他也是

2022-04-09 11:00 UTC, Yesterday17 requested changes
不懂虹虹，有哪些是 OP/ED 也可以在 track 上标上 tag（

2022-04-09 11:11 UTC, Yesterday17 approved these changes

2022-04-09 16:23 UTC, merged