IM@S Part 2
ProjectAnni/repo pull request #97
Opened 2022-05-01 12:33 UTC by Yesterday17

2022-05-04 03:11 UTC, Last-Order approved these changes
LGTM

2022-05-04 03:11 UTC, Last-Order commented on album/COZC-583.toml
> +title = "READY!!(M@STER VERSION)"
```suggestion
title = "READY!!(M@STER VERSION)"
tags = ["OP"]
```

2022-05-04 03:11 UTC, Last-Order commented on album/COZC-597.toml
> +title = "CHANGE!!!! (M@STER VERSION)"
```suggestion
title = "CHANGE!!!! (M@STER VERSION)"
tags = ["OP"]
```

2022-05-04 03:11 UTC, Last-Order commented on album/COCX-36899.toml
> +title = "READY!! (TV Size)"
```suggestion
title = "READY!! (TV Size)"
tags = ["OP"]
```

2022-05-04 14:38 UTC, tuzi3040 requested changes

2022-05-04 14:38 UTC, tuzi3040 commented on album/IMAS-2001.toml
> +title = "THE IDOLM@STER LAWSON ORIGINAL DRAMA DISK"
```suggestion
title = "THE IDOLM@STER LAWSON ORIGINAL DRAMA"
```

2022-05-05 06:17 UTC, tuzi3040 approved these changes

2022-05-05 06:18 UTC, merged